# Generated by Django 3.0.8 on 2020-08-27 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_auto_20200823_1415'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='profile_complete',
            field=models.CharField(default='level-0', max_length=7),
        ),
    ]
