# Generated by Django 3.0.8 on 2020-08-27 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_userprofile_profile_complete'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='allowed_to_rate',
            field=models.BooleanField(default=False),
        ),
    ]
