# Generated by Django 3.0.8 on 2020-08-04 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_auto_20200804_1436'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='hobbies',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='hobbies',
            field=models.ManyToManyField(blank=True, to='profiles.Hobby'),
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='sports',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='sports',
            field=models.ManyToManyField(blank=True, to='profiles.Sport'),
        ),
    ]
