# Generated by Django 3.0.8 on 2020-08-27 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_userprofile_allowed_to_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_complete',
            field=models.CharField(default='lvl-0', max_length=7),
        ),
    ]
