# Generated by Django 3.0.8 on 2020-08-17 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_auto_20200804_1510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(choices=[('GIRL', 'girl'), ('BOY', 'boy'), ('NONE', 'prefer not to say')], default='None', max_length=25),
            preserve_default=False,
        ),
    ]
