# Generated by Django 3.0.8 on 2020-08-30 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_auto_20200827_1943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='date_of_birth',
            field=models.DateField(blank=True, default=None, help_text='You can add site to 2 categories', null=True),
        ),
    ]
