# Generated by Django 3.0.8 on 2020-08-18 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0023_rating_sports'),
        ('profiles', '0006_auto_20200817_1715'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='favorites',
            field=models.ManyToManyField(to='books.Book'),
        ),
    ]
