# Generated by Django 3.0.8 on 2020-08-19 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0024_book_reading'),
        ('profiles', '0007_userprofile_favorites'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='favorites',
            field=models.ManyToManyField(blank=True, to='books.Book'),
        ),
    ]
