# Generated by Django 3.0.8 on 2020-09-08 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0008_auto_20200830_1502'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='age_in_years',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
