# Generated by Django 3.0.8 on 2020-09-08 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0009_userprofile_age_in_years'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='age_in_years',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
