# Generated by Django 3.0.8 on 2020-08-22 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0012_auto_20200821_0942'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='hobbies_and_sports_known',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='hobbies_known',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='only_hobbies_known',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='only_sports_known',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='sports_known',
            field=models.BooleanField(default=False),
        ),
    ]
