# Generated by Django 3.0.8 on 2020-08-22 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0013_auto_20200822_1053'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='no_hobbies_and_sports_known',
            field=models.BooleanField(default=False),
        ),
    ]
