# Generated by Django 3.0.8 on 2020-08-23 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_remove_book_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='testfield',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
