# Generated by Django 3.0.8 on 2020-08-23 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_book_avg_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='testfield',
        ),
        migrations.AddField(
            model_name='book',
            name='boys_avg_rating',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=2),
        ),
        migrations.AddField(
            model_name='book',
            name='boys_number_of_ratings',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='girls_avg_rating',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=2),
        ),
        migrations.AddField(
            model_name='book',
            name='girls_number_of_ratings',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='number_of_ratings',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
