# Generated by Django 3.0.8 on 2020-08-24 07:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_auto_20200823_1752'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='avg_rating',
            new_name='rating',
        ),
        migrations.AddField(
            model_name='book',
            name='most_liked_by',
            field=models.CharField(default='not known yet', max_length=15),
        ),
        migrations.AddField(
            model_name='book',
            name='recommended_age',
            field=models.CharField(default='not known yet', max_length=254),
        ),
        migrations.AlterField(
            model_name='rating',
            name='book_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='book_id_of_rating', to='books.Book'),
        ),
    ]
