# Generated by Django 3.0.8 on 2020-08-07 11:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_auto_20200804_1510'),
        ('books', '0009_book_test_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='rated_by',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='profiles.UserProfile'),
        ),
    ]
