# Generated by Django 3.0.8 on 2020-08-09 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_auto_20200804_1510'),
        ('books', '0010_auto_20200807_1353'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='test_rating',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='rated_by',
        ),
        migrations.AddField(
            model_name='rating',
            name='rated_by',
            field=models.ManyToManyField(blank=True, to='profiles.UserProfile'),
        ),
    ]
