# Generated by Django 3.0.8 on 2020-08-24 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0010_auto_20200824_1053'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='age_mode',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
