# Generated by Django 3.0.8 on 2020-08-24 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0011_book_age_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='age_mode',
            field=models.CharField(default='not available', max_length=54),
        ),
    ]
