# Generated by Django 3.0.8 on 2020-08-09 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_auto_20200804_1510'),
        ('books', '0011_auto_20200809_1605'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rating',
            name='rated_by',
        ),
        migrations.AddField(
            model_name='rating',
            name='rated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='profiles.UserProfile'),
        ),
    ]
