# Generated by Django 3.0.8 on 2020-08-25 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0012_auto_20200824_1304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='most_liked_by',
            field=models.CharField(choices=[('girls', 'girls'), ('boys', 'boys'), ('boys and girls', 'boys and girls')], default='not known yet', max_length=15),
        ),
    ]
