# Generated by Django 3.0.8 on 2020-08-10 08:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_auto_20200804_1510'),
        ('books', '0012_auto_20200809_1646'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='rating_all',
        ),
        migrations.RemoveField(
            model_name='book',
            name='rating_boys',
        ),
        migrations.RemoveField(
            model_name='book',
            name='rating_girls',
        ),
        migrations.AddField(
            model_name='book',
            name='rated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='profiles.UserProfile'),
        ),
    ]
