# Generated by Django 3.0.8 on 2020-08-10 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_auto_20200804_1510'),
        ('books', '0013_auto_20200810_1039'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='rated_by',
        ),
        migrations.AddField(
            model_name='book',
            name='rated_by',
            field=models.ManyToManyField(blank=True, to='profiles.UserProfile'),
        ),
    ]
