# Generated by Django 3.0.8 on 2020-08-10 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0014_auto_20200810_1055'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='rated_by',
        ),
    ]
