# Generated by Django 3.0.8 on 2020-08-26 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0015_auto_20200825_2054'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='most_disliked_by',
            field=models.CharField(choices=[('girls', 'girls'), ('boys', 'boys'), ('boys and girls', 'boys and girls')], default='not known yet', max_length=15),
        ),
    ]
