# Generated by Django 3.0.8 on 2020-08-26 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0017_remove_book_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='most_disliked_by',
            field=models.CharField(choices=[('girls', 'girls'), ('boys', 'boys'), ('boys and girls', 'boys and girls')], default='not known yet', max_length=150),
        ),
        migrations.AlterField(
            model_name='book',
            name='most_liked_by',
            field=models.CharField(choices=[('girls', 'girls'), ('boys', 'boys'), ('boys and girls', 'boys and girls')], default='not known yet', max_length=150),
        ),
    ]
