# Generated by Django 3.0.8 on 2020-08-26 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0018_auto_20200826_1521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='most_disliked_by',
            field=models.CharField(choices=[('girls', 'girls'), ('boys', 'boys'), ('boys and girls', 'all, this most be really bad...')], default='not known yet', max_length=150),
        ),
        migrations.AlterField(
            model_name='book',
            name='most_liked_by',
            field=models.CharField(choices=[('girls', 'girls'), ('boys', 'boys'), ('boys and girls', 'all, this most be really bad...')], default='not known yet', max_length=150),
        ),
    ]
