# Generated by Django 3.0.8 on 2020-08-10 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0018_auto_20200810_1530'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rating',
            old_name='age_rating',
            new_name='age_rating_months',
        ),
        migrations.AddField(
            model_name='rating',
            name='age_rating_years',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
    ]
