# Generated by Django 3.0.8 on 2020-08-10 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_auto_20200804_1510'),
        ('books', '0019_auto_20200810_1606'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='hobbies',
            field=models.ManyToManyField(blank=True, to='profiles.Hobby'),
        ),
    ]
