# Generated by Django 3.0.8 on 2020-08-26 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0019_auto_20200826_1523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='most_disliked_by',
            field=models.CharField(choices=[('girls', 'girls'), ('boys', 'boys'), ('all, this most be really bad...', 'all, this most be really bad...')], default='not known yet', max_length=150),
        ),
        migrations.AlterField(
            model_name='book',
            name='most_liked_by',
            field=models.CharField(choices=[('girls', 'girls'), ('boys', 'boys'), ('all, this most be really bad...', 'all, this most be really bad...')], default='not known yet', max_length=150),
        ),
    ]
