# Generated by Django 3.0.8 on 2020-08-18 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0020_rating_hobbies'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rating',
            name='hobbies',
        ),
        migrations.AddField(
            model_name='rating',
            name='hobbies',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
    ]
