# Generated by Django 3.0.8 on 2020-08-27 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0020_auto_20200826_1524'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='star_rating_all',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=2),
        ),
        migrations.AddField(
            model_name='book',
            name='star_rating_boys',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=2),
        ),
        migrations.AddField(
            model_name='book',
            name='star_rating_girls',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=2),
        ),
    ]
