# Generated by Django 3.0.8 on 2020-08-28 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0021_auto_20200827_1008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='most_liked_by',
            field=models.CharField(choices=[('girls', 'girls'), ('boys', 'boys'), ('all, this most be really good!', 'all, this most be really good!')], default='not known yet', max_length=150),
        ),
    ]
