# Generated by Django 3.0.8 on 2020-08-18 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_auto_20200817_1715'),
        ('books', '0021_auto_20200818_1619'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rating',
            name='hobbies',
        ),
        migrations.AddField(
            model_name='rating',
            name='hobbies',
            field=models.ManyToManyField(blank=True, to='profiles.Hobby'),
        ),
    ]
