# Generated by Django 3.0.8 on 2020-08-28 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0022_auto_20200828_0932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='most_disliked_by',
            field=models.CharField(choices=[('not known yet', 'not known yet'), ('girls', 'girls'), ('boys', 'boys'), ('all, this most be really bad...', 'all, this most be really bad...')], default='not known yet', max_length=150),
        ),
        migrations.AlterField(
            model_name='book',
            name='most_liked_by',
            field=models.CharField(choices=[('not known yet', 'not known yet'), ('girls', 'girls'), ('boys', 'boys'), ('all, this most be really good!', 'all, this most be really good!')], default='not known yet', max_length=150),
        ),
    ]
