# Generated by Django 3.0.8 on 2020-08-18 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_auto_20200817_1715'),
        ('books', '0022_auto_20200818_1641'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='sports',
            field=models.ManyToManyField(blank=True, to='profiles.Sport'),
        ),
    ]
