# Generated by Django 3.0.8 on 2020-08-28 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0023_auto_20200828_0948'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='image',
            new_name='image_detail',
        ),
        migrations.AddField(
            model_name='book',
            name='image_result',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='book',
            name='image_thumb',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
