# Generated by Django 3.0.8 on 2020-08-28 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0024_auto_20200828_1043'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='image_result',
            new_name='image_card',
        ),
    ]
