# Generated by Django 3.0.8 on 2020-08-20 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0025_remove_book_reading'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='age_rating_months',
            field=models.CharField(blank=True, max_length=3),
        ),
        migrations.AlterField(
            model_name='rating',
            name='age_rating_years',
            field=models.CharField(blank=True, max_length=3),
        ),
    ]
