# Generated by Django 3.0.8 on 2020-08-20 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0026_auto_20200820_1209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='age_rating_months',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='rating',
            name='age_rating_years',
            field=models.IntegerField(),
        ),
    ]
